db.ventas.drop()
db.ventas.insertMany([
    {
        id:1,
        articulo:"sudadera",
        precio_articulo: 20,
        precio_coste: 10,
        cliente: "Juan Francisco",
        unidades: 15,
        empleado_vendedor: "Francisco Texeira",
        fecha_de_venta: new Date (2021-10-12),
        mejor_articulo: false,
        beneficios: false},
        {
        id:2,
        articulo:"camisa",
        precio_articulo: 28,
        precio_coste: 12,
        cliente: "Juan Francisco",
        unidades: 8,
        empleado_vendedor: "Francisco Texeira",
        fecha_de_venta: new Date (2021-08-28),
        mejor_articulo: true,
        beneficios: false},
        {
        id:3,
        articulo:"vaquero",
        precio_articulo: 18,
        precio_coste: 8,
        cliente: "Juan Francisco",
        unidades: 50,
        empleado_vendedor: "Francisco Texeira",
        fecha_de_venta: new Date (2021-06-02),
        mejor_articulo: true,
        beneficios: true},
        {
        id:4,
        articulo:"camiseta",
        precio_articulo: 5,
        precio_coste: 0.5,
        cliente: "Daniel Garcia",
        unidades: 90,
        empleado_vendedor: "Lucia Blanco",
        fecha_de_venta: new Date (2021-11-09),
        mejor_articulo: false,
        beneficios: true},
        {
        id:5,
        articulo:"Zapato",
        precio_articulo: 28.5,
        precio_coste: 13,
        cliente: "Daniel Garcia",
        unidades: 20,
        empleado_vendedor: "Lucia Blanco",
        fecha_de_venta: new Date (2021-05-31),
        mejor_articulo: false,
        beneficios: false},
        {
        id:6,
        articulo:"Polo",
        precio_articulo: 7,
        precio_coste: 1.5,
        cliente: "Daniel Garcia",
        unidades: 18,
        empleado_vendedor: "Lucia Blanco",
        fecha_de_venta: new Date (2021-07-18),
        mejor_articulo: false,
        beneficios: true},
        {
        id:7,
        articulo:"Corbata",
        precio_articulo: 2,
        precio_coste: 0.20,
        cliente: "Paco Pacheco",
        unidades: 15,
        empleado_vendedor: "Francisco Texeira",
        fecha_de_venta: new Date (2021-10-12),
        mejor_articulo: false,
        beneficios: false},
        {id:8,
        articulo:"Conjunto",
        precio_articulo: 17.5 ,
        precio_coste: 8,
        cliente: "Paco Pacheco",
        unidades: 50,
        empleado_vendedor: "Lucia Blanco",
        fecha_de_venta: new Date (2021-08-28),
        mejor_articulo: false,
        beneficios: true},
        {
        id:9,
        articulo:"Traje",
        precio_articulo: 75,
        precio_coste: 50,
        cliente: "Benito Perez",
        unidades: 17,
        empleado_vendedor: "Maximiliano Rodrigez",
        fecha_de_venta: new Date (2021-05-07),
        mejor_articulo: true,
        beneficios: false},
        {
        id:10,
        articulo:"Chaqueta",
        precio_articulo: 32,
        precio_coste: 14,
        cliente: "Benito Perez",
        unidades: 20,
        empleado_vendedor: "Maximiliano Rodrigez",
        fecha_de_venta: new Date (2021-11-14),
        mejor_articulo: true,
        beneficios: true}
     ] 
        )